const crypto=require('crypto');
function fail(c,m,code='INVALID_PLAN'){if(c){const e=new Error(m);e.code=code;throw e;}}
function buildPlan(input){
  fail(!input||typeof input!=='object','planning input required');fail(typeof input.demandVersion!=='string'||typeof input.inventoryVersion!=='string'||typeof input.recipeVersion!=='string','versioned demand, inventory, and recipes required');
  const inventory=new Map((input.inventory||[]).map(i=>[i.ingredientId,Number(i.availableQty)]));const recipes=new Map((input.recipes||[]).map(r=>[r.sku,r]));const requirements=new Map();const lots=new Set();const allergens=new Set();const lines=[];
  for(const demand of input.demand||[]){const recipe=recipes.get(demand.sku);fail(!recipe,`recipe missing for ${demand.sku}`);fail(!Number.isFinite(Number(demand.quantity))||Number(demand.quantity)<=0,`invalid demand for ${demand.sku}`);fail(!Number.isFinite(Number(recipe.yieldQty))||Number(recipe.yieldQty)<=0,`invalid yield for ${demand.sku}`);const batches=Math.ceil(Number(demand.quantity)/Number(recipe.yieldQty));for(const ing of recipe.ingredients||[]){const qty=Number(ing.qtyPerBatch)*batches;fail(!Number.isFinite(qty)||qty<0,`invalid ingredient quantity for ${ing.ingredientId}`);requirements.set(ing.ingredientId,(requirements.get(ing.ingredientId)||0)+qty);if(ing.lotId)lots.add(ing.lotId);for(const a of ing.allergens||[])allergens.add(a);}lines.push({sku:demand.sku,quantity:Number(demand.quantity),batches,dueAt:demand.dueAt});}
  const shortages=[...requirements].filter(([id,qty])=>(inventory.get(id)||0)<qty).map(([ingredientId,requiredQty])=>({ingredientId,requiredQty,availableQty:inventory.get(ingredientId)||0}));const capacity=Number(input.capacityBatches);fail(!Number.isInteger(capacity)||capacity<1,'positive integer capacityBatches required');const totalBatches=lines.reduce((s,l)=>s+l.batches,0);const maintenanceBlocks=(input.equipment||[]).filter(e=>e.maintenanceDue||e.status!=='available').map(e=>e.id);
  const plan={inputVersions:{demand:input.demandVersion,inventory:input.inventoryVersion,recipes:input.recipeVersion},lines,requirements:Object.fromEntries([...requirements].sort()),sourceLots:[...lots].sort(),allergens:[...allergens].sort(),shortages,capacity:{requiredBatches:totalBatches,availableBatches:capacity},maintenanceBlocks,qualityHolds:[...new Set(input.qualityHolds||[])].sort(),substitutions:[]};
  const blockers=[...(shortages.length?['INVENTORY_SHORTAGE']:[]),...(totalBatches>capacity?['CAPACITY_EXCEEDED']:[]),...(maintenanceBlocks.length?['EQUIPMENT_MAINTENANCE']:[]),...(plan.qualityHolds.length?['QUALITY_HOLD']:[])];return{plan,status:blockers.length?'blocked':'pending_approval',blockers,digest:crypto.createHash('sha256').update(JSON.stringify(plan)).digest('hex')};
}
function recordApproval(existing,context){fail(existing.status==='blocked','blocked plan cannot be approved');fail(!['qa_manager','production_manager','admin'].includes(context.role),'authorized approver required','FORBIDDEN');fail(String(context.actorId)===String(existing.createdBy),'planner cannot approve own plan','SEPARATION_OF_DUTIES');fail(typeof context.signature!=='string'||context.signature.length<16,'signed approval required');const approvals={...(existing.approvals||{})};if(context.role==='qa_manager'||context.role==='admin')approvals.qa={actorId:String(context.actorId),signature:context.signature};if(context.role==='production_manager'||context.role==='admin')approvals.production={actorId:String(context.actorId),signature:context.signature};return{approvals,status:approvals.qa&&approvals.production?'executable':'pending_approval'};}
function validateHaccpRelease(input){fail(!Array.isArray(input.criticalControls)||!input.criticalControls.length,'critical control records required');for(const c of input.criticalControls)fail(!c.name||c.withinLimit!==true||!c.recordedAt||!c.recordedBy,`critical control ${c.name||'unknown'} is incomplete`);fail(typeof input.allergenLabelVerification!=='string'||input.allergenLabelVerification.length<8,'allergen label verification required');return{criticalControls:input.criticalControls,allergenLabelVerification:input.allergenLabelVerification,released:true};}
function traceRecall(lotId,plans){fail(typeof lotId!=='string'||!lotId,'lotId required');return plans.filter(p=>(p.plan.sourceLots||[]).includes(lotId)).map(p=>({planId:p.id,status:p.status,skus:p.plan.lines.map(l=>l.sku)}));}
module.exports={buildPlan,recordApproval,validateHaccpRelease,traceRecall};
